# Generated by Django 6.0.3 on 2026-03-05 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marque', models.CharField(max_length=100, verbose_name='Marque')),
                ('modele', models.CharField(max_length=100, verbose_name='Modèle')),
                ('annee', models.IntegerField(verbose_name='Année')),
                ('prix_location', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prix location (par jour)')),
                ('prix_vente', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prix vente')),
                ('type_offre', models.CharField(choices=[('location', 'Location'), ('vente', 'Vente')], max_length=10, verbose_name="Type d'offre")),
                ('description', models.TextField(verbose_name='Description détaillée')),
                ('disponibilite', models.BooleanField(default=True, verbose_name='Disponible')),
                ('date_ajout', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout")),
            ],
            options={
                'verbose_name': 'Voiture',
                'verbose_name_plural': 'Voitures',
                'ordering': ['-date_ajout'],
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='media/', verbose_name='Fichier')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Vidéo')], max_length=5, verbose_name='Type de média')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'upload")),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medias', to='cars.car', verbose_name='Voiture associée')),
            ],
            options={
                'verbose_name': 'Média',
                'verbose_name_plural': 'Médias',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
