# Generated by Django 6.0.3 on 2026-06-10 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150, verbose_name='Nom complet')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('telephone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('sujet', models.CharField(max_length=200, verbose_name='Sujet')),
                ('message', models.TextField(verbose_name='Message')),
                ('date_envoi', models.DateTimeField(auto_now_add=True, verbose_name="Date d'envoi")),
                ('lu', models.BooleanField(default=False, verbose_name='Lu')),
            ],
            options={
                'verbose_name': 'Message de contact',
                'verbose_name_plural': 'Messages de contact',
                'ordering': ['-date_envoi'],
            },
        ),
        migrations.RemoveField(
            model_name='car',
            name='disponibilite',
        ),
        migrations.AddField(
            model_name='car',
            name='statut',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('reserve', 'Réservé'), ('vendu', 'Vendu')], default='disponible', max_length=20, verbose_name='Statut'),
        ),
        migrations.CreateModel(
            name='TestDriveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150, verbose_name='Nom complet')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('telephone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('date_souhaitee', models.DateTimeField(blank=True, null=True, verbose_name="Date souhaitée pour l'essai")),
                ('statut_demande', models.CharField(choices=[('en_attente', 'En attente'), ('valide', 'Validé'), ('annule', 'Annulé'), ('termine', 'Terminé')], default='en_attente', max_length=20, verbose_name='Statut de la demande')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de la demande')),
                ('voiture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_drives', to='cars.car', verbose_name='Véhicule')),
            ],
            options={
                'verbose_name': "Demande d'essai",
                'verbose_name_plural': "Demandes d'essai",
                'ordering': ['-date_creation'],
            },
        ),
    ]
